// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Twitter.Persistence;

#nullable disable

namespace Twitter.Persistence.Migrations
{
    [DbContext(typeof(TwitterDbContext))]
    [Migration("20230118201458_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Twitter.Domain.Entities.TwitterStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hashtag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfTweets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TwitterStatistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 1, 18, 15, 14, 58, 778, DateTimeKind.Local).AddTicks(2629),
                            Hashtag = "#brasil#saopaulo#competition#influencer#influencermarketing#fridayfeeling#MondayMotivation#tbt#traveltuesday#vegan",
                            NumberOfTweets = 1000
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 1, 17, 15, 14, 58, 778, DateTimeKind.Local).AddTicks(2698),
                            Hashtag = "#usa#tampa#competition#influencer#influencermarketing#fridayfeeling#MondayMotivation#tbt#traveltuesday#vegan",
                            NumberOfTweets = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
